name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Récupération du code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Étape 2 : Configuration de Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # Étape 3 : Installation des dépendances Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Installation de PyInstaller
          pip install pillow       # Installation de Pillow
          pip install -r examplePlugin/requirements.txt  # Installation des dépendances depuis requirements.txt

# Les étapes suivantes (comme la construction et le téléchargement) ne sont pas incluses dans ce résumé.
