name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ÉTAPE 1 : Récupération du code source du dépôt
      - name: RECUPERATION DU REPERTOIRE
        uses: actions/checkout@v3
      
      # ÉTAPE 2 : Configuration de Python 3.12
      - name: CONFIGURATION DE PYTHON 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      # ÉTAPE 3 : Installation des dépendances Python
      - name: INSTALLATION DES DEPENDANCES PYTHON
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Installation de PyInstaller
          pip install pillow       # Installation de Pillow
          pip install -r requirements.txt  # Installation des dépendances depuis requirements.txt
          
      # ÉTAPE 4 : Création de tpp avec tppbuild
      - name: CREATION DU TPP AVEC TPPBUILD
        run: |
          python3 client/xplane_plugin_for_touch_portal_build.py

      # ÉTAPE 5 : Affichage de la structure des fichiers et répertoires
      - name: AFFICHAGE DE LA STRUCTURE DES FICHIERS ET REPERTOIRES
        run: |
          tree ./Better Raids  # Utilisation de tree pour afficher la structure sous Linux/macOS
